AppLugares/urls.py
from django.urls import path

from AppLugares.views import render_posts, post_detail

app_name = "AppLugares"

urlpatterns = [
    path('', render_posts, name='post'),
    path('<int:post_id>', post_detail, name="post_detail")
]

Proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include
from AppWeb.views import home, login_request, base, about, usuarios
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', base, name="AppWebBase"),
    path('about/', about, name="AppWebAbout"),
    path('home/', home, name="AppWebHome"),
    path('login/', login_request, name="Login"),
    path('AppLugares/', include('AppLugares.urls')),
    path('usuarios/', usuarios, name="AppWebUsuarios"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppLugares/models.py
from django.db import models


class Post(models.Model):

    id = models.AutoField(primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    autor = models.CharField(max_length=30)
    lugar = models.CharField(max_length=30)
    ciudad = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=1000)
    imagen = models.ImageField(upload_to='Lugares/imagenes/')
    url = models.URLField(blank=True)


class Comentario(models.Model):

    id = models.AutoField(primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    autor = models.CharField(max_length=30)
    comentario = models.TextField()
    post_id = models.IntegerField()

AppWeb/models.py
from django.db import models


class Home(models.Model):
    pass


class About(models.Model):
    pass


class Usuario(models.Model):

    id = models.AutoField(primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField()

    def __str__(self):
        return f"Usuario: {self.nombre}, Apellido: {self.apellido}"

AppLugares/forms.py
from django import forms


class ComentarioForm(forms.Form):

    autor = forms.CharField(max_length=30)
    comentario = forms.CharField(max_length=200)

AppWeb/forms.py
from django import forms


class UsuarioForm(forms.Form):

    nombre = forms.CharField(min_length=3, max_length=30)
    apellido = forms.CharField(min_length=3, max_length=30)
    email = forms.EmailField()

AppLugares/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comentario
from AppLugares.forms import ComentarioForm


def render_posts(request):
    posts = Post.objects.all()

    return render(request, "AppLugares/posts.html", {'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        mi_formulario = ComentarioForm(request.POST)

        if mi_formulario.is_valid():
            informacion = mi_formulario.cleaned_data
            comentario_save = Comentario(
                autor=informacion['autor'],
                comentario=informacion['comentario'],
                post_id=post_id
            )

            comentario_save.save()

    all_comentarios = Comentario.objects.filter(post_id__icontains=post_id)
    context = {
        "form": ComentarioForm(),
        "post": post,
        "comentarios": all_comentarios
    }
    return render(request, 'AppLugares/post_detail.html', context=context)

AppWeb/views.py
from django.shortcuts import render
from AppWeb.models import Usuario
from AppWeb.forms import UsuarioForm
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate


def home(request):
    return render(request, "AppWeb/home.html")


def base(request):
    return render(request, "base.html")


def about(request):
    return render(request, "AppWeb/about.html")


def usuarios(request):
    if request.method == "POST":
        mi_formulario = UsuarioForm(request.POST)

        if mi_formulario.is_valid():
            informacion = mi_formulario.cleaned_data
            usuario_save = Usuario(
                nombre=informacion['nombre'],
                apellido=informacion['apellido'],
                email=informacion['email']
            )
            usuario_save.save()

    all_usuarios = Usuario.objects.all()
    context = {
        "usuarios": all_usuarios,
        "form": UsuarioForm()
    }
    return render(request, "AppWeb/usuarios.html", context=context)


def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():  # Si pasó la validación de Django

            usuario = form.cleaned_data.get('username')
            contrasenia = form.cleaned_data.get('password')

            user = authenticate(username=usuario, password=contrasenia)

            if user is not None:
                login(request, user)

                return render(request, "AppWeb/home.html", {"mensaje": f"Bienvenido {usuario}"})
            else:
                return render(request, "AppWeb/home.html", {"mensaje": "Datos incorrectos"})
        else:
            return render(request, "AppWeb/home.html", {"mensaje": "Formulario erroneo"})
    form = AuthenticationForm()

    return render(request, "AppWeb/login.html", {"form": form})

templates/AppLugares/post_detail.html
{% extends "base.html" %}
{% block contenido_cambia %}
{% load static %}

<div>
<!-- page header -->
    <header class="header">
        <div class="overlay"></div>
        <div class="header-content">
            <h1>{{post.lugar}}</h1>
        </div>
    </header><!-- end of page header -->

</div>


<div class="container p-4">
    <div class="card card-body">
        <div class="row">
            <div class="col-3">
                <img src="{{post.imagen.url}}" alt="{{post.lugar}}" class="img-fluid">
            </div>
            <div class="col-9">
                <h6>{{post.created}}</h6>
                <p>{{post.descripcion}}</p>
            </div>
        </div>
    </div>
    <div>
        <h4> Comentarios: </h4>
        </br>
    </div>


    <div>
        <div>

            {% if comentarios %}
                {% for comentario in comentarios %}


                    <h6>autor: {{comentario.autor}}</h6>
                    <p>fecha: {{comentario.created}}</p>
                    <h6>comentario: {{comentario.comentario}}</h6>
                    <p>-----------------------------------------------</p>
                {% endfor %}
            {% else %}

                <h6>No hay comentarios que mostrar</h6>
            {% endif %}

            </br>
            <h6>-------------------------------------------------------</h6>
            </br>

            <h6>Nuevo Comentario:</h6></br>

            <form action="{% url 'AppLugares:post_detail' post.id %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Enviar">
            </form>

        </div>
    </div> <!-- end of page container -->
</div>

{% endblock %}

templates/AppLugares/posts.html
{% extends "base.html" %}
{% block contenido_cambia %}
{% load static %}

<div>
<!-- page header -->
    <header class="header">
        <div class="overlay"></div>
        <div class="header-content">
            <h1 class="header-title">Posts</h1>
            <p>Acá puedes ver todos los lugares que están posteados dentro del sitio web.</p>

        </div>
    </header><!-- end of page header -->
</div>


{% for post in posts %}

    <div class="container p-4">
        <div class="card card-body">
            <div class="row">
                <div class="col-3">
                    <img src="{{post.imagen.url}}" alt="{{post.lugar}}" class="img-fluid">
                </div>

                <div class="col-9">
                    <h2>{{post.lugar|upper}}</h2>
                    <h6>{{post.created}}</h6>
                    <p>{{post.descripcion|truncatechars:100}}</p>

                    <a class="btn btn-primary btn-sm" href="{% url 'AppLugares:post_detail' post.id %}">"Ver mas"</a>
                </div>

            </div>

        </div>
    </div>


{% endfor %}

{% endblock %}

templates/AppWeb/about.html
{% extends "base.html" %}
{% block contenido_cambia %}
{% load static %}

<div>
<!-- page header -->
    <header class="header">
        <div class="overlay"></div>
        <div class="header-content">
            <h1 class="header-title">¿Quienes somos?</h1>
            <p class="header-subtitle">Soy Andrés Kaulen, una persona que está aprendiendo a usar Python, me gusta Chile y su naturaleza, por lo que he creado un portal para publicar y poder comentar fotos de naturaleza Chilena usando el lenguaje aprendido. </p>
        </div>
    </header><!-- end of page header -->
</div>
{% endblock %}

templates/AppWeb/direcciones.html
DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Dorang landing page.">
    <meta name="author" content="Devcrud">
    <title>Fertilizatech</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'AppWeb/assets/vendors/themify-icons/css/themify-icons.css' %}">

    <!-- Bootstrap + Dorang main styles -->
	<link rel="stylesheet" href="{% static 'AppWeb/assets/css/dorang.css' %}">

</head>

<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home" class="dark-theme">

    <!-- page navbar -->
    <nav class="page-navbar affix-top" data-spy="affix" data-offset-top="10">
        <ul class="nav-navbar container">
            <li class="nav-item"><a href="/usuarios" class="nav-link">Usuarios</a></li>
            <li class="nav-item"><a href="/direcciones#" class="nav-link">Direcciones</a></li>
            <li class="nav-item"><a href="/home" class="nav-link"><img src="{% static 'AppWeb/assets/imgs/Agrocompra-Isotipo1.png' %}" alt="Download"></a></li>
            <li class="nav-item"><a href="/solicitudes" class="nav-link">Solicitudes</a></li>
            <li class="nav-item search">
                <a href="javascript:void(0)" class="nav-link search-toggle"><i class="ti-search"></i> Search</a>
                <div class="search-wrapper">
                    <form>
                        <input type="search" class="form-control" name="" placeholder="hit enter to search">
                    </form>
                </div>
            </li>
        </ul>
    </nav><!-- end of page navbar -->


    <!-- page container -->
     <div>
        <div class="col-md-10 col-lg-8 m-auto">
            <h6 class="title mb-4 mt-5 pt-5">Formulario de Direcciones</h6>
            <p class="mb-5">2do formulario.</p>
            {% block contenido_cambia %}
                <form action="{% url 'AppWebDirecciones' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Enviar">
                </form>
                {% if direccion %}
                    {% for direccion in direcciones %}
                        <P>calle: {{ direccion.calle }}</P>
                        <P>numero: {{ direccion.numero }}</P>
                        <P>ciudad: {{ direccion.ciudad }}</P>
                    {% endfor %}
                {% else %}
                    <h1>No hay direcciones en el momento</h1>
                {% endif %}
            {% endblock %}
        </div>
    </div> <!-- end of page container -->

    <!--footer & pre footer -->
    <div class="contact-section">
        <div class="overlay"></div>
        <!-- container -->

            <!-- footer -->
            <footer class="footer">
                <p class="infos">&copy; Hecho para la clase de Coder</i> </a></p>
                <span>|</span>
                <div class="links">
                    <a href="#">About</a>
                    <a href="#">Explore</a>
                    <a href="#">Journal</a>
                </div>
            </footer><!-- end of footer -->

        </div><!-- end of container -->
    </div><!-- end of pre footer -->

    <!-- core  -->
    <script src="{% static 'AppWeb/assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'AppWeb/assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

    <!-- bootstrap affix -->
    <script src="{% static 'AppWeb/assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

    <!-- Dorang js -->
    <script src="{% static 'AppWeb/assets/js/dorang.js' %}"></script>

</body>

templates/AppWeb/home.html
{% extends "base.html" %}
{% block contenido_cambia %}
{% load static %}




<div>
<!-- page header -->
    <header class="header">
        <div class="overlay"></div>
        <div class="header-content">
            <h1 class="header-title"> Lugares del sur de chile. </h1>
            <p class="header-subtitle">Es un pequeño portal en donde puedes compartir lugares del sur de Chile y comentarlos!</p>

        </div>
    </header><!-- end of page header -->


    <!-- page container -->
    <div class="container page-container">
        <div class="col-md-10 col-lg-8 m-auto">
            <h6 class="title mb-4">¿Qué hacemos?</h6>
            <p class="mb-5">Te ayudamos en la forma de conseguir la cantidad del producto X que quieras. Los puedes comprar directo al vendedor, sin intermediarios. Lo hacemos de manera sencilla, rápida y fácil. Suena bonito, pero así es. Somos cracks &#128526.</p>
        </div>

    <div class="col-md-10 col-lg-8 m-auto">
        <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim.</p>
    </div>


        <!-- row -->
        <div class="row mb-4">
            <div class="col-md-4">
                <a href="javascript:void(0)" class="overlay-img">
                    <img src="{% static 'AppWeb/assets/imgs/img-1.1.jpg' %}" alt="Download free trap">
                    <div class="overlay"></div>
                    <div class="des">
                        <h1 class="title">Libertad absoluta</h1>
                        <h6 class="subtitle">nadie queda fuera</h6>
                        <p>Imaginate que lo ocupas todos los días, junto con todos tus seres queridos. Es así de fácil.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="javascript:void(0)" class="overlay-img">
                    <img src="{% static 'AppWeb/assets/imgs/img-2.2.jpg' %}" alt="Download free bootstrap 4 landing page, free boootstrap 4 templates, Download free bootstrap 4.1 landing page, free boootstrap 4.1.1 templates, weber Landing page">
                    <div class="overlay"></div>
                    <div class="des">
                        <h1 class="title">Sin costos </h1>
                        <h6 class="subtitle">leíste bien</h6>
                        <p>No hacemos cobros a los productores de Chile, y no significa que cobremos a los extranjeros, es solo que por el momento no estamos en otros países.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="javascript:void(0)" class="overlay-img">
                    <img src="{% static 'AppWeb/assets/imgs/img-3.3.jpg' %}" alt="Download free bootstrap 4 landing page, free boootstrap 4 templates, Download free bootstrap 4.1 landing page, free boootstrap 4.1.1 templates, weber Landing page">
                    <div class="overlay"></div>
                    <div class="des">
                        <h1 class="title">Atendido por personas</h1>
                        <h6 class="subtitle">No somos solo una máquina</h6>
                        <p>Entendemos que hoy queremos cuidar nuestro tiempo, pero además, también cuidamos las amistades. Por esta razón somos un canal del agro y estamos disponibles para ayudarte SIEMPRE.</p>
                    </div>
                </a>
            </div>
        </div><!-- end of row -->

        <<!-- <a href="#">Load More <i class="ti-angle-double-right angle"></i></a> -->




        <!-- row -->
        <div class="row mb-5">
            <div class="col-md-6">
                <a href="javascript:void(0)" class="card">
                    <img src="{% static 'AppWeb/assets/imgs/blog-1.jpg' %}" class="card-img" alt="Download free bootstrap 4 landing page, free boootstrap 4 templates, Download free bootstrap 4.1 landing page, free boootstrap 4.1.1 templates, weber Landing page">
                    <div class="card-body">
                        <h6 class="card-subtitle">30 June, 2018</h6>
                        <h3 class="card-title">Eiusmod
                        tempor</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-6">
                <a href="javascript:void(0)" class="card">
                    <img src="{% static 'AppWeb/assets/imgs/blog-2.jpg' %}" class="card-img" alt="Download free bootstrap 4 landing page, free boootstrap 4 templates, Download free bootstrap 4.1 landing page, free boootstrap 4.1.1 templates, weber Landing page">
                    <div class="card-body">
                        <h6 class="card-subtitle">29 June, 2018</h6>
                        <h3 class="card-title">Ut minim veniam</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua.</p>
                    </div>
                </a>
            </div>
        </div><!-- end of row -->

        <a href="#">All Posts <i class="ti-angle-double-right angle"></i></a>

    </div>
</div>
{% endblock %}

templates/AppWeb/login.html
{% extends "base.html" %}
{% block contenido_cambia %}
{% load static %}

<!-- page header -->
    <header class="header">
        <div class="overlay"></div>
        <div class="header-content">
            <h1>Login</h1>
        </div>
    </header><!-- end of page header -->

</div>

<div class="container p-4">
    <div>

        <form action="" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Iniciar Sesion</button>
        </form>
    </div>
</div>


{% endblock %}

templates/AppWeb/usuarios.html
{% extends "base.html" %}
{% block contenido_cambia %}
{% load static %}

<div>
<!-- page header -->
    <header class="header">
        <div class="overlay"></div>
        <div class="header-content">
            <h1 class="header-title">Usuarios</h1>
        </div>
    </header><!-- end of page header -->
</div>

<div class="container p-4">
    <div>
        <div>
            <form action="{% url 'AppWebUsuarios' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Enviar">
            </form>
        <br><hr>

        {% if usuarios %}
            {% for usuario in usuarios %}
                <P>nombre: {{ usuario.nombre }}</P>
                <P>apellido: {{ usuario.apellido }}</P>
                <P>email: {{ usuario.email }}</P>
            {% endfor %}
        {% else %}
            <h1>No hay usuarios en el momento</h1>
        {% endif %}
        </div>
    </div>
</div> <!-- end of page container -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Dorang landing page.">
    <meta name="author" content="Devcrud">
    <title>Fertilizatech</title>
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'AppWeb/assets/vendors/themify-icons/css/themify-icons.css' %}">

    <!-- Bootstrap + Dorang main styles -->
	<link rel="stylesheet" href="{% static 'AppWeb/assets/css/dorang.css' %}">

</head>

<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home" class="dark-theme">

    <!-- page navbar -->
    <nav class="page-navbar affix-top" data-spy="affix" data-offset-top="10">
        <ul class="nav-navbar container">
            <li class="nav-item"><a href="/home" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="/AppLugares" class="nav-link">Lugares</a></li>
            <li class="nav-item"><a href="/usuarios" class="nav-link">usuarios</a></li>
            <li class="nav-item"><a href="/about" class="nav-link">about</a></li>
            <li class="nav-item"><a href="/login" class="nav-link">login</a></li>
            <li class="nav-item search">
                <a href="javascript:void(0)" class="nav-link search-toggle"><i class="ti-search"></i> Search</a>
                <div class="search-wrapper">
                    <form>
                        <input type="search" class="form-control" name="" placeholder="hit enter to search">
                    </form>
                </div>
            </li>
        </ul>
    </nav><!-- end of page navbar -->

    <!-- Body -->

        {% block contenido_cambia %}
            <h1>No se encuentra contenido disponible</h1>
        {% endblock %}
    </div>


    <!--footer & pre footer -->
    <div class="contact-section">
        <div class="overlay"></div>
        <!-- container -->
        <div class="container">

            <!-- footer -->
            <footer class="footer">
                <p class="infos">&copy; <script>document.write(new Date().getFullYear())</script>, Modificado por Andrés Kaulen </i> </p>
                <span>|</span>  
                <div class="links">
                    <a href="#">About</a>
                    <a href="#">Explore</a>
                    <a href="#">Journal</a>
                </div>
            </footer><!-- end of footer -->

        </div><!-- end of container -->
    </div><!-- end of pre footer -->

    <!-- core  -->
    <script src="{% static 'AppWeb/assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'AppWeb/assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

    <!-- bootstrap affix -->
    <script src="{% static 'AppWeb/assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

    <!-- Dorang js -->
    <script src="{% static 'AppWeb/assets/js/dorang.js' %}"></script>

</body>
</html>